### ISSUE TITLE
NotifcationListernerService

### ISSUE THREAD

**Issue by vivekkumar** [Fleker/AndroidTVNotification#1]
https://stackoverflow.com/questions/28425581/android-tv-notification-access

is this solved? if yes, can you please let me know how because I am also facing same issue.

**Comment by Fleker** [comment]
It's not solved as far as I know

**Comment by Fleker** [comment]
Although I believe the original point of the project was to use the phone to receive notifications and the TV would then receive a app-level notification, ignoring the issue completely.
